### ISSUE TITLE
Debugging for .NET Core does not calculate the output path correctly with TargetName

### ISSUE THREAD

**Issue by jnm2** [dotnet/sdk#11173]
I've been using `<TargetName>ActualOutputFileNameWithoutExtension</TargetName>` as a good way to control the output filename independently from the assembly's actual name. Once in a while, for style reasons, this is handy. Sometimes I'll need a long namespace and matching assembly name containing the namespace, but the output file name looks kinda silly.

As @boriscallens [discovered](https://stackoverflow.com/a/44188341), when you try to debug, the executable path is not properly calculated and debugging does not start. I don't know if he's using the old or new csproj SDK, but I did discover an issue with the new project system:

I've always happened to use this in the new csproj and targeting .NET Framework, where the debug executable path *is* properly calculated. It's when you target .NET Core that it stops working.

Runs and debugs as expected:

```c#
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net47</TargetFramework>
    <OutputType>exe</OutputType>
    <TargetName>TestFilename</TargetName>
  </PropertyGroup>

</Project>
```

Does not run or debug, unless you remove the `<TargetName>`:

```c#
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp11</TargetFramework>
    <OutputType>exe</OutputType>
    <TargetName>TestFilename</TargetName>
  </PropertyGroup>

</Project>
```

Specifically, my expectation would be that debugging would honor `<TargetFileName>` calculated in Microsoft.Common.CurrentVersion.targets.

**Comment by jibbers42** [comment]
Here is a simpler set of steps to reproduce the issue, but for running instead of debugging - hopefully the same fix for both.

```
==> dotnet --version 
5.0.300

==> dotnet new console -o TargetNameIssue
The template "Console Application" was created successfully.
...

==> cd TargetNameIssue

==> dotnet run
Hello World!
```
Edit TargetNameIssue.csproj and add `<TargetName>CustomName</TargetName>` within the `ProperyGroup` section.
```
==> dotnet run
The application to execute does not exist: '/home/jibbers42/code/testbeds/TargetNameIssue/bin/Debug/net5.0
/TargetNameIssue.dll'.

==> ls bin/Debug/net5.0/
CustomName.dll  ref              TargetNameIssue.deps.json               TargetNameIssue.runtimeconfig.json
CustomName.pdb  TargetNameIssue  TargetNameIssue.runtimeconfig.dev.json
```

It would be great to see a fix released for this issue :slightly_smiling_face:

**Comment by burnsba** [comment]
Still an issue with .net 6

**Comment by AnthonyMastrean** [comment]
Still seeing this on .NET 7.0. I have a console app created from the template (`dotnet new console`) and added just the `TargetName`.

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <TargetName>my-agent</TargetName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>
</Project>
```

And, of course, `dotnet run` is not happy about that:

```
The application to execute does not exist: 'D:\ExampleConsoleApp\bin\Debug\net7.0\ExampleConsoleApp.dll'.
```

When I look in the `bin` folder, I see some of the files have been renamed and some have not.

```
ExampleConsoleApp.deps.json
ExampleConsoleApp.exe
ExampleConsoleApp.runtimeconfig.json
my-agent.dll
my-agent.pdb
System.CommandLine.dll
```

The `dotnet info` output:

```
.NET SDK:
 Version:   7.0.310
 Commit:    585715708c
```

**Comment by baronfel** [comment]
My suspicion is that we don't have a full handle on the relationship between `TargetName`, `TargetFileName`, and `TargetPath` from the `Microsoft.Common.CurrentVersion.targets`. We need to define the relationship between these items, determine which one is the actual _intended_ value to use for the `RunArguments` in the SDK's [RunArguments inference](https://github.com/dotnet/sdk/blob/cc53925cb2d170612d86b8f9a19985139a501f64/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L1008-L1047), then make any change there.
