### ISSUE TITLE
dotnet process consuming CPU when no dotnet programs should be running

### ISSUE THREAD

**Issue by rshillington** [dotnet/sdk#2179]
## Details about the problem
.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.105/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

## Steps to reproduce
* Open ActivityMonitor and observe that there are no processes named "dotnet" running.
* dotnet new console
* dotnet run

## Expected Behaviour
* Hello World

## Actual Behaviour
* Hello World
* Extra dotnet process running and consuming all CPU cycles as seen in Activity Monitor.  This process never stops.

**Comment by livarcocc** [comment]
This is likely the VBCSCompiler and that the process lingers around is expected. The fact that it is consuming CPU is an issue that has been addressed and a fix for it will be available in our 2.1.200 release.

**Comment by livarcocc** [comment]
In 2.1.300, you can shutdown all long running build processes spun by dotnet by running `dotnet build-server shutdown`.

**Comment by rshillington** [comment]
I would also add that the following:
```
dotnet publish
dotnet bin/Debug/netcoreapp2.0/publish/hello/hello.dll

```
does not start up this background dotnet process.  Is this the only work around?  `dotnet run` is very handy, but having to constantly shutdown this background process is less than ideal.

**Comment by livarcocc** [comment]
You can set `<UseSharedCompilation>false</UseSharedCompilation>` in your project or in a Directory.Build.props file (if you want this for all your projects in that folder) to turn it off. dotnet publish will start the vbcscompiler as well, it might not have in this case because msbuild detected that your files are up to date and did not invoke the compiler.

**Comment by seeess1** [comment]
I'm using the .NET 6.0 SDK for Mac (Intel processor) along with VS Code version 1.63.2 and was tinkering with some simple examples in C#. Then I closed out of VS Code and ran `dotnet build-server shutdown` but my laptop sounds like it's working really hard right now and the top three processes in my activity monitor still show `dotnet` (consuming around 97% of my CPU usage). I've tried the `dotnet build-server shutdown` command a couple times and each time it says:

```
VB/C# compiler server shut down successfully.
MSBuild server shut down successfully.
```

Is there something else I should be doing to get `dotnet` to stop running?

**Comment by KalleOlaviNiemitalo** [comment]
@seeess1 there are <https://github.com/dotnet/sdk/issues/23349> and <https://github.com/dotnet/sdk/issues/23267> open for excessive CPU consumption on macOS.

**Comment by seeess1** [comment]
> @seeess1 there are #23349 and #23267 open for excessive CPU consumption on macOS.

Thanks a bunch! Will keep an eye on those threads.
