### ISSUE TITLE
Unable to load System.IO.Compression.ZipFile when targeting 4.7.1 after the new conflict resolution changes.

### ISSUE THREAD

**Issue by joperezr** [dotnet/sdk#2292]
It was reported internally that after the new changes that went in for conflict resolution, apps are running into an issue where they can't find System.IO.Compression.ZipFile v.4.0.3.0 at runtime. The issue seems to be that the new logic will add a Reference to the platform ZipFile assembly, which will cause a conflict with the package reference and RAR will suggest a binding redirect to the 4.0.3.0 version. The problem is that if that binding redirect is added, is that System.IO.Compression.ZipFile is not part of the support package, so we won't be able to find an assembly that matches that version inbox(because the inbox version is 4.0.0.0). There are a few ways of working around this, one would be to manually add a binding redirect to your project that binds down to the platform version, that way assembly will always be able to load.
```xml
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.IO.Compression.ZipFile" publicKeyToken="b77a5c561934e089" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

The other option, is to add System.IO.Compression.ZipFile to the support package version 4.0.3.0 and that way the binding redirect that gets added automatically will just work fine.
cc: @dsplaisted

**Comment by dsplaisted** [comment]
@AlexGhiondea @ericstj What do you suggest for fixing this?

**Comment by ericstj** [comment]
>  the new logic will add a Reference to the platform ZipFile assembly

Why is this happening if the version from the package is higher than the one in the platform?  Seems to me that the platform should lose if the package version was higher.

**Comment by joperezr** [comment]
Actually it looks like the Platform version is higher, so it seems like my description above is not accurate. Here is the messasge from conflict resolution:
```
Encountered conflict between 'Platform:System.IO.Compression.ZipFile.dll' and 'CopyLocal:C:\Users\daplaist.REDMOND\.nuget\packages\system.io.compression.zipfile\4.3.0\lib\net46\System.IO.Compression.ZipFile.dll'.  Choosing 'Platform:System.IO.Compression.ZipFile.dll' because AssemblyVersion '4.0.3.0' is greater than '4.0.2.0'.
```

**Comment by dsplaisted** [comment]
I think what's happening is that the reference assembly has a version of 4.0.3.0, but the version in the framework is 4.0.0.0.  The unification table makes this work if you compile against 4.0.3.0, but apparently if you have a binding redirect to 4.0.3.0, the unification table doesn't kick in.  This seems broken, as it should be valid to have a binding redirect to the version of a DLL that is in the targeting pack for the version of .NET you're targeting.

**Comment by joperezr** [comment]
The fact that unification table doesn't kick in is by design, the actual bug here is that for some reason, RAR is deciding to suggest a binding redirect when it sees a conflict version for SYstem.IO.Compression.ZipFile. This is unique to this assembly, as this doesn't happen with for example System.Runtime, which is a facade as well and has the exact same situation (Reference assembly version is higher than 4.0.0.0 but the actual inbox implementation is 4.0.0.0) but RAR doesn't suggest redirects for this ever. I believe there is something unique about how RAR treats System.IO.Compression.ZipFile, and in figuring out why is the fix of this issue.

**Comment by joperezr** [comment]
FYI @ericstj and I did look a bit into RAR's code, and it does seem to have a mechanism of filtering out assemblies that are inbox so that it won't suggest binding redirects for them, but it doesn't seem to be doing it for ZipFile's case.

**Comment by joperezr** [comment]
Figured it out. The issue is the conflict resolution task emits single name references with extensions (for example: System.Runtime.dll instead of System.Runtime). This causes RAR to not filter out the binding redirects as it believes that the assembly is not inbox, and then we get into this problem. Fixing the conflict resolution task to not include the extension on the references should fix the issue.

**Comment by dsplaisted** [comment]
@joperezr I updated the conflict resolution so there is no .dll in the added reference, but I'm still getting the same warning/failure.  I think it may be because RAR is reading the app.config file and sees the binding redirect in it.

@AlexGhiondea FYI

**Comment by dsplaisted** [comment]
@joperezr @AlexGhiondea I think the fix is to add the following to the .targets file that expands the .NET Standard facades:

```xml
  <Target Name="RemoveZipFileSuggestedRedirect"
          BeforeTargets="GenerateBindingRedirects"
          DependsOnTargets="ResolveAssemblyReferences"
          Condition="'$(_TargetFrameworkVersionWithoutV)' == '4.7.1'">
    <ItemGroup>
      <SuggestedBindingRedirects Remove="System.IO.Compression.ZipFile, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
    </ItemGroup>
    
  </Target>
```

Let's discuss this in person.

**Comment by dsplaisted** [comment]
Here are more details about what I think is going on:

I believe this only happens when a binding redirect to version 4.0.0.0 of System.IO.Compression.ZipFile has been added as a workaround to [this issue](https://github.com/Microsoft/dotnet/blob/master/releases/net471/KnownIssues/623552-BCL%20Higher%20assembly%20versions%20that%204.0.0.0%20for%20System.IO.Compression.ZipFile%20cannot%20be%20loaded%20without%20a%20binding%20redirect.md):

```xml
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.IO.Compression.ZipFile" publicKeyToken="b77a5c561934e089" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

I think (but haven't confirmed by looking at the code) that ResolveAssemblyReference is reading the app.config, and seeing version 4.0.0.0 of the assembly in the graph because it's the target of a binding redirect.  When there's a framework reference to the assembly, that is for version 4.3.0.0, so it suggests a redirect to that version, which overrides the one that was in the source app.config and causes a runtime error loading the assembly.

Before #2221 was fixed by #2250, there wouldn't be any framework reference to the assembly, so RAR wouldn't see the 4.3.0.0 version of the assembly in the graph, and hence wouldn't suggest the binding redirect.

So I do think removing the suggested binding redirect in this case is probably the correct fix.  RAR's view of the world (based on the reference assemblies it sees) leads it to suggesting an incorrect binding redirect.
