### ISSUE TITLE
Failure to publish WASM when project source path contains blank spaces - Post-upgrade VS 2022 to 17.2.4

### ISSUE THREAD

**Issue by NonoSparc** [dotnet/sdk#26061]
Since upgrade of Visual Studio 2022 from 17.2.3 to 17.2.4 on june 15th, I cannot publish any Blazor Web Application project anymore.

This goes for new and existing projects. Even a simple publish to folder fails with error message:

`C:\Program Files\dotnet\sdk\6.0.301\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(614,5): Error MSB6006: "dotnet.exe" exited with code 1.
`

After hours of frustating attempts, I found that it was related to the location of my projects. **Parent path to my dev folder contained blank spaces!**

Changing VS MSBuild output verbosity, I found that the error was related to Blazor WebAssembly publish artifacts compression task:

```
...
Compressing Blazor WebAssembly publish artifacts. This may take a while...
Creating directory "obj\Release\net6.0\compress\".
C:\Program Files\dotnet\dotnet.exe "C:\Program Files\dotnet\sdk\6.0.301\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\..\tools\net6.0\Microsoft.NET.Sdk.BlazorWebAssembly.Tool.dll" brotli
-s
C:\Dev\With Space\BlazorAppSol\BlazorApp\Client\bin\Release\net6.0\wwwroot\_framework\blazor.webassembly.js
-o
C:\Dev\With Space\BlazorAppSol\BlazorApp\Client\obj\Release\net6.0\compress\N6++qccl.br
...
Unrecognized command or argument 'Space\BlazorAppSol\BlazorApp\Client\bin\Release\net6.0\wwwroot\_framework\blazor.webassembly.js'.
...
C:\Program Files\dotnet\sdk\6.0.301\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(614,5): Error MSB6006: "dotnet.exe" exited with code 1.
```

The above output was produced by creating a new Blazor Web Assembly project under a root folder with path 'C:\Dev\With Space\' and publishing it to relative folder 'bin\Release\net6.0\publish\'.

Is this a known issue?

Configuration:
Windows 10 Enterprise 21H2 Build 19044.1766
Visual Studio Enterprise 2022 64-bit version 17.2.4
Blazor WebAssembly App project with .NET 6 and ASP.NET Core host

**Comment by wkellar** [comment]
Same problem here since upgrade of Visual Studio 2022 from 17.2.3 to 17.2.4 yesterday. Removing White space in file path fixed it.

**Comment by craigbrown** [comment]
We're having the same problem in Azure DevOps Pipelines since yesterday, using v6.0.301 of the SDK. The `publish` fails on the exact same step (`Compressing Blazor WebAssembly publish artifacts`). As a result our pipeline now fails to run. It was working in v6.0.300.

We don't have any whitespace in our project's path name, but in Azure DevOps Pipelines the `dotnet` tool is run from `C:\Program Files\dotnet\dotnet.exe` which does have a space. Running the pipeline with more verbose output shows many lines like this:
```
Unrecognized command or argument 'Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.6\runtimes\browser-wasm\lib\net6.0\Microsoft.CSharp.dll'.
Unrecognized command or argument 'Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.6\runtimes\browser-wasm\lib\net6.0\Microsoft.VisualBasic.Core.dll'.
Unrecognized command or argument 'Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.6\runtimes\browser-wasm\lib\net6.0\Microsoft.VisualBasic.dll'.
Unrecognized command or argument 'Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.6\runtimes\browser-wasm\lib\net6.0\Microsoft.Win32.Primitives.dll'.
Unrecognized command or argument 'Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.6\runtimes\browser-wasm\lib\net6.0\Microsoft.Win32.Registry.dll'.
Unrecognized command or argument 'Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.6\runtimes\browser-wasm\lib\net6.0\mscorlib.dll'.
Unrecognized command or argument 'Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.6\runtimes\browser-wasm\lib\net6.0\netstandard.dll'.
...
```
which does suggest it's the space in `Program Files` which is causing the issue.

**Comment by baronfel** [comment]
Hey folks, can anyone impacted please upload a [binlog](http://aka.ms/binlog) with details? This really help us speed up the process of identifying where the issue with space handling is being introduced, so we can route it to the correct team for triage and resolution.

**Comment by craigbrown** [comment]
@baronfel here's one from a minimal reproducible example I set up.

My issue is very slightly different - the whitespace is not in the project path but in the path to dotnet.exe. I assume it's related though.

I also discovered that the issue only occurs when my Blazor WASM app's `csproj` file contains the setting `<PublishTrimmed>false</PublishTrimmed>`. Maybe that helps narrow down the problem.

[out.binlog.zip](https://github.com/dotnet/sdk/files/8928876/out.binlog.zip)

**Comment by baronfel** [comment]
Thanks folks - we believe this was inadvertently introduced with an update to System.CommandLine that changed the default processing of response files. The binlog above was _very_ helpful in tracking this down @craigbrown, so thank you for that! 

[sample-bad-response-file.txt](https://github.com/dotnet/sdk/files/8929000/sample-bad-response-file.txt)

Heres what's been generated in the current bad state, I'm talking with the System.CommandLine team and figuring out how we want to resolve this. Will report back with options and how we intend to go forward.

**Comment by SantosVictorero** [comment]
Definitely the problem is with Task BrotliCompress; I created two test projects, one with not spaces and one with spaces.

Here is the binlog file of the one with spaces:

[BlazorAppWithSpaces_Release_AnyCPU_Build_2022-06-17T20_23_21.3052265-04_00.zip](https://github.com/dotnet/sdk/files/8931892/BlazorAppWithSpaces_Release_AnyCPU_Build_2022-06-17T20_23_21.3052265-04_00.zip)

**Comment by baronfel** [comment]
Done, thanks for the reminder!

**Comment by vijayrkn** [comment]
@baronfel - Based on the previous comments, this doesn't look like an issue in the websdk targets.  What would be the best label for this?

**Comment by LeonSpors** [comment]
> > > You can add `global.json` file with
> > > ```
> > > {
> > >   "sdk": {
> > >     "version": "6.0.300"
> > >   }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > see https://docs.microsoft.com/en-us/dotnet/core/tools/global-json
> > 
> > 
> > That works ! Added global.json with version 6.0.203 in the solution folder, deleted all /bin and /obj folders in solution projects => I can now publish successfully !
> 
> global.json file wont work if its inside the path/folder which has space issue so keep it in top most possible folder.

The solution is to copy the folder and rename it. Just for the sake of publishing.

**Comment by maxgsamson** [comment]
+1 same problem really a big bad waste of time... nasty problem!

Fixed mine by downgrading from 301 to 300 SDK... 301 has security patch so that is not a long term solution MS need to fix that at the next release.

For people in my situation here what i have done. Instruction above wasn't clear especially for people who are not used to play with dotnet sdks... i think most of us rely on VS IDE to install/update .netx.x and move on to develop...

i didn't have sdk 300 installed...
1. https://dotnet.microsoft.com/en-us/download/dotnet/6.0
2. Download and Install .NET 6.0.5 which will install sdk 300
3. Tools => NuGet Package Manager => Package Manager Console
4. type "dotnet new globaljson --force --sdk-version 6.0.300"
6. Build => Clean and Delete Bin/Obj
7. Restart Visual Studio
8. Publish it should work, it did for me anyway

**Comment by dsplaisted** [comment]
We're sorry about this regression, and yes, we do expect to fix this in the next release (302).

Here's the relevant PR: https://github.com/dotnet/sdk/pull/26204

**Comment by SantosVictorero** [comment]
Today I installed Visual Studio update 17.2.6 which deleted the DotNet SDK version 6.0.300. 

![image](https://user-images.githubusercontent.com/1824105/178783979-696cd35f-5dd6-41c1-a620-de3e9b4ac6be.png)

I removed my global.json with 6.0.300 and tested with 302 but as mentioned before, the error is still there:

![image](https://user-images.githubusercontent.com/1824105/178784688-78d0fac8-3a54-4a2a-8e9d-3c8a4c2d7d5a.png)

I tried to install 6.0.300 again and I got the following error:
[6990:45CC][2022-07-13T12:34:41]e000: Error 0x80070666: Cannot install a product when a newer version is installed.

Should I remove the 6.0.302 SDK  to reinstall 6.0.300 or is another workaround?

**Comment by baronfel** [comment]
@SantosVictorero you'll have to install 6.0.300 manually and then use a global.json file to 'pin' to that version specifically in order to workaround this bug. Echoing @dsplaisted above, 6.0.303 in August will contain the fix for this and at that point you could remove your global.json.

**Comment by SantosVictorero** [comment]
Thanks @baronfel, it works like a charm, again! :+1:

Download and manually install .NET: 
https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net60#download-and-manually-install

**Comment by maxgsamson** [comment]
> Today I installed Visual Studio update 17.2.6 which deleted the DotNet SDK version 6.0.300.
> 
> ![image](https://user-images.githubusercontent.com/1824105/178783979-696cd35f-5dd6-41c1-a620-de3e9b4ac6be.png)
> 
> I removed my global.json with 6.0.300 and tested with 302 but as mentioned before, the error is still there:
> 
> ![image](https://user-images.githubusercontent.com/1824105/178784688-78d0fac8-3a54-4a2a-8e9d-3c8a4c2d7d5a.png)
> 
> I tried to install 6.0.300 again and I got the following error: [6990:45CC][2022-07-13T12:34:41]e000: Error 0x80070666: Cannot install a product when a newer version is installed.
> 
> Should I remove the 6.0.302 SDK to reinstall 6.0.300 or is another workaround?
You dont have to delete the 6.0.302... just install 6.0.300
Check my post above https://github.com/dotnet/sdk/issues/26061#issuecomment-1167503779

**Comment by baronfel** [comment]
I'm going to close this one in favor of #26026, which it is a duplicate of.

**Comment by HClausing** [comment]
I've updated my VS2022 Preview yesterday, and my (production) VS 2022 is failing to publish with this same error on SDK 6.0.400.

The global.json file forcing the 6.0.300 version solved the problem also.

I'm just taking a note for the possibility of the bug is back on the 6.0.400.

**Comment by baronfel** [comment]
I've reopened the original issue due to this.

**Comment by EricB-ASI** [comment]
Is there a workaround that we can use in the meantime? The latest version of VS removed 6.0.300 and I cannot manually install it due to having a newer version installed. I tried updating the global.json file to use 6.0.303 but that did not work.

Any suggestions would be appreciated.

**Comment by baronfel** [comment]
The only workaround is working in a path that doesn't contain spaces, unfortunately.

**Comment by SantosVictorero** [comment]
Probably you can use version 6.0.203 as a work around too: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.203-windows-x64-installer.

**Comment by EricB-ASI** [comment]
I was able to implement the workaround @SantosVictorero suggested, but wondering when this will be fixed?

**Comment by PanamaHeur** [comment]
Sorry my english.

The problem is with the Maximum Path Length Limitation. To solve this problem You just need change the project path to a small path like C:\MyProject, and that it :-) 

I hope this help to every one...

**Comment by NonoSparc** [comment]
...
> The problem is with the Maximum Path Length Limitation. To solve this problem You just need change the project path to a small path like C:\MyProject, and that it :-)
> 
...
The length of the path can be an issue, but the real problem is when you have blank spaces within: "C:\Dev\My Project\" is enough to cause the bug!

**Comment by baronfel** [comment]
A status update on this - we have an approved fix for servicing that we will merge one the September releases go out, so the final fix for this will be in the October releases of the .NET SDK.
