### ISSUE TITLE
.NET 8 RC2 does not honor ignore-failed-sources flag when running dotnet tool install 

### ISSUE THREAD

**Issue by aaronwjha** [dotnet/sdk#36473]
When installing dotnet tools with a configured nuget source that fails to load, the --ignore-failed-sources flag is not honored. 

### Description

```bash
PS C:\Users\***\source\repos\jhld_reporting_templates> dotnet tool install JackHenry.Report.Fake --add-source "c:\Users\***\downloads" --global --ignore-failed-sources --verbosity diag 
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/jackhenry.report.fake/index.json
[NuGet Manager] [Info]   NotFound https://api.nuget.org/v3/registration5-gz-semver2/jackhenry.report.fake/index.json 61ms
[NuGet Manager] [Warning] The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`
[NuGet Manager] [Warning] The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`
[NuGet Manager] [Info]   GET https://***.com/artifactory/api/nuget/v3/nuget/FindPackagesById()?id='jackhenry.report.fake'&semVerLevel=2.0.0
[NuGet Manager] [Info]   Unauthorized https://***.com/artifactory/api/nuget/v3/nuget/FindPackagesById()?id='jackhenry.report.fake'&semVerLevel=2.0.0 107ms
Unhandled exception: NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://pkgs.dev.azure.com/*****/nuget/v3/index.json.
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass15_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)     
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
   --- End of inner exception stack trace ---
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at NuGet.Protocol.PackageMetadataResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.GetPackageMetadataAsync(PackageSource source, String packageIdentifier, Boolean includePrerelease, CancellationToken cancellationToken)
   at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.GetMatchingVersionInternalAsync(String packageIdentifier, IEnumerable`1 packageSources, VersionRange versionRange, CancellationToken cancellationToken)
   at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.GetBestPackageVersionAsync(PackageId packageId, VersionRange versionRange, PackageSourceLocation packageSourceLocation)
   at Microsoft.DotNet.Cli.ToolPackage.ToolPackageDownloader.<>c__DisplayClass8_0.<InstallPackage>b__0()
   at Microsoft.DotNet.Cli.TransactionalAction.Run[T](Func`1 action, Action commit, Action rollback)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)

```

### Configuration

.NET 8 RC2
Windows 10 Ent, x64

### Regression?

This works properly with .NET 7

**Comment by dsplaisted** [comment]
@JL03-Yue This is probably because the `RestoreActionConfig` isn't being created correctly based on the command line options.  I think we recently looked at another similar bug with the NoCache option.

**Comment by frederikstonge** [comment]
Still an issue with 8.0.100 release.

**Comment by ricardoMTC** [comment]
I normally would use the **--ignore-failed-sources** but I'm also getting some errors upon using it. Also using 8.0.100

![image](https://github.com/dotnet/sdk/assets/94381746/bdeeca51-e3d1-49f8-b260-572fde556b62)

**Comment by ChristoWolf** [comment]
Hi!

Chiming in to say that I am also observing the same issue.

**Comment by PaulVrugt** [comment]
same here, any workaround?

**Comment by ChristoWolf** [comment]
@PaulVrugt: I think a work-around would be to create a basic Nuget.Config file only containing the nuget.org feed and to pass this then to the command.

**Comment by PaulVrugt** [comment]
@ChristoWolf yes thank you, I found a similar workaround

**Comment by ChristoWolf** [comment]
I also had time now to try out this work-around, works fine.
Still, it would be great if this issue would be resolved as soon as possible.

**Comment by marci4** [comment]
Any update on this issue?

Is there a way on how we can speed up the process here?

**Comment by hannahbellelee** [comment]
I tend to think this is an issue unrelated to .NET8 as a whole. I have been getting failures on dotnet tool install before I installed .NET8.. It first started showing up in Visual Studio Code in my powershell terminal, so I thought it was something specifically related to VSCode, but when I opened a terminal or a powershell window outside of VSCode Id get the same thing....And always with the telerik nuget package....And what I am installing has nothing to do with the telerik nuget package.
![image](https://github.com/dotnet/sdk/assets/146478400/9ad65c38-6663-42e5-ac91-0554791af55c)

I have been using a small workaround for months, because I thought this would get fixed eventually. So what I have to do is open:

```xml
C:\Users\dev007\AppData\Roaming\NuGet\NuGet.Config
```

And comment out the telerik key( I have 9 other keys in there and none of them cause an error except the telerik one):

```xml
<!-- <add key="Telerik NuGet" value="https://nuget.telerik.com/v3/index.json" /> -->
```

 Save the file, then rerun 

```xml
[dev007]$ dotnet tool install -g SOME_PACKAGE_TO_INSTALL
```

The install worked perfectly: 
![image](https://github.com/dotnet/sdk/assets/146478400/de460ce3-a636-46cf-8933-bec803bc7e20)

but now the Nuget Source is not available in Visual Studio, so I have to open the file back up and uncomment it then save the file again...

**Comment by ChristoWolf** [comment]
@hannahbellelee: I think your problem is a bit different from the reported one here, correct me if I'm wrong.

The issue here is specifically caused by the newest. NET DSK.

**Comment by ChristoWolf** [comment]
Hi @JL03-Yue!

Has there been any progress?
We have to use the work-around in quite a few places currently.

**Comment by marci4** [comment]
Just wanna confirm that this is still an issue with 8.0.101

**Comment by frederikstonge** [comment]
Here's my workaround. Create a nuget-tools.config with this :
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To
    inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

Then use this : 
```bash
dotnet tool install --global <package-name> --configfile nuget-tools.config
```

**Comment by wexman** [comment]
I'm kind of losing hope that this will be fixed, as it is still not working today.
*If* you're going at it, how about fixing --interactive as well?

**Comment by mcallaghan-geotab** [comment]
> _If_ you're going at it, how about fixing --interactive as well?
^ that isn't how software works :) - _ADDING_ scope makes it less likely to get fixed :)

**Comment by baronfel** [comment]
Just as a status update, this is one of a number of auth/feed related issues that we'll be looking at in the near term, but after the team finishes landing a few of their already-in-flight work items.

**Comment by jabaker88** [comment]
Also experiencing this issue

**Comment by hannahbellelee** [comment]
> @hannahbellelee: I think your problem is a bit different from the reported one here, correct me if I'm wrong.
> 
> The issue here is specifically caused by the newest .NET SDK.

No this was not specific to a new version. The same thing was happening before the update... But once I noticed it wasnt fixed with the update, i posted it...There are workarounds, but there really shouldnt have to be...

**Comment by hannahbellelee** [comment]
I went in to my Control Panel , into credential manager for windows, and updated any credentials for any nuget packages...then from an admin powershell reinstalled nuget...and nuget cli and after that things seemed to work which is very odd, but in any case... I will let you know  if i get a chance to test again later.

**Comment by byronbayer** [comment]
yep this is still happening on our pipelines when trying to install ReportGenerator tool in the pipeline.
Our workaround is to add the following to the nuget.config file
```
<disabledPackageSources>
        <add key="my-org-package-location" value="true" />
</disabledPackageSources>
```

**Comment by hannahbellesheart** [comment]
Everytime I ran into this, it always seemed to be related to the telerik feed AUTHENTICATION. I never get an error on the devexpress feed, which also requires authentication. or any other feed. So the only thing that has fixed this for me is the following...And when I say fixed, i mean I have not had a single error since running this. Of course replace the username and password with your own....


Open the Package Manager Console in VS2022.
At the PM> prompt, use the following compact.
`PM>NuGet Sources Update -Name 'Telerik NuGet' -Source 'https://nuget.telerik.com/v3/index.json' -UserName 'YURTLRK@EMAILADDY.COM' -Password 'YUR_TELERIK_PW'`

**Comment by epenet** [comment]
For those who have this issue on CI / Azure Pipeline, and are looking for a workaround, I have found that it is possible to add a preliminary job in the configuration to force NuGet to authenticate against the Azure private feeds :

```yaml
jobs:
  - job: Build
    steps:
      (...)

      # NuGet authenticate
      - task: NuGetAuthenticate@1

      # Install report generator
      - script: 'dotnet tool install -g dotnet-reportgenerator-globaltool --verbosity detailed --ignore-failed-sources'
```

With this workaround in place, the private feeds no longer fail, and `--ignore-failed-sources` becomes redundant.

**Comment by rhooijkaas** [comment]
Still bugged in SDK 8.0.203
![afbeelding](https://github.com/dotnet/sdk/assets/129306297/2df0fd61-8fdb-4f10-b901-86f746768f4b)

**Comment by reijerh** [comment]
Still bugged in SDK 8.0.203
![afbeelding](https://github.com/dotnet/sdk/assets/129306297/2df0fd61-8fdb-4f10-b901-86f746768f4b)

**Comment by ChristoWolf** [comment]
Hi!

Are there any new plans on when a fix for this can be released?

**Comment by JZechy** [comment]
Any updates on this?

**Comment by yokrysty** [comment]
don't expect from an extremely birocratic company to solve such a simple issue too soon

**Comment by ChristoWolf** [comment]
Hi!

Are there any new plans on when a fix for this can be released?

**Comment by ChristoWolf** [comment]
Looks like it's planned for [milestone 8.0.4xx](https://github.com/dotnet/sdk/milestone/85).

**Comment by marcpopMSFT** [comment]
Old issue triage: ignore failed sources should be working with tool installs. Tested locally and it's working in 9 and 10

**Comment by ChristoWolf** [comment]
@marcpopMSFT: Does this mean it will not be fixed for .NET 8?

**Comment by marcpopMSFT** [comment]
Unlikely as we're not prioritizing most changes for 8 with 10 coming out shortly. CC @baronfel though we'd have to isolate the change we made in 9 to fix this (I think it was one of forginds as I recall him fixing it but I'd have to dig a bit).

**Comment by afscrome** [comment]
@marcpopMSFT  I can still reproduce this in .Net 10 preview 7.  Run the following once with a network connection to populate your nuget pacakges folder, than run it a second time with flight mode on / ethernet unplugged.  

```
dotnet tool exec --ignore-failed-sources --source https://api.nuget.org/v3/index.json --source $env:NUGET_PACKAGES --verbosity diag dotnet-ef
```

Expected Results: as long as `dotnet ef` was already in your nuget packages folder, this should work, however `dotnet tool exec` fails with a "No such host is known" error, suggesting it hasn't ignored the failed package source.

```
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/index.json
[NuGet Manager] [Info] An error was encountered when fetching 'GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/index.json'. The request will now be retried.
No such host is known. (api.nuget.org:443)
  No such host is known.
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/index.json
[NuGet Manager] [Info] An error was encountered when fetching 'GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/index.json'. The request will now be retried.
No such host is known. (api.nuget.org:443)
  No such host is known.
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/index.json
Unhandled exception: No such host is known. (api.nuget.org:443)
```

**Comment by marcpopMSFT** [comment]
Is it only tool exec that fails in this mode? Mind creating a new issue to track that as tool exec is new so it may be limited to that code path.

**Comment by afscrome** [comment]
HI @marcpopMSFT I'm sure this was failing when I tried previously, but it is behaving today - `dotnet tool install` does seem to be ok - `dotnet tool install dotnet-ef --add-source s:\_packages\nuget\ --add-source https://api.nuget.org/v3/index.json --ignore-failed-sources`

https://github.com/dotnet/sdk/issues/50579 was raised for the tool exec issue.
