### ISSUE TITLE
UserSecretsId attribute not generated when M.E.C.UserSecrets reference transitively

### ISSUE THREAD

**Issue by anurse** [dotnet/sdk#4007]
## Overview

The logic that injects the `UserSecretsIdAttribute` appears to only work if the `Microsoft.Extensions.Configuration.UserSecrets` package is reference directly (or through the ASP.NET Core runtime). The worker template references it transitively through `Microsoft.Extensions.Hosting` and the attribute is never generated and user secrets are not loaded.

This was originally reported by customers: https://github.com/aspnet/Extensions/issues/2743 https://github.com/aspnet/AspNetCore.Docs/issues/14315

## Repro Steps

Repro repo (just clone and skip to step 3): https://github.com/anurse/UserSecretsInWorkerRepro

1. `dotnet new worker`
2. Edit `ExecuteAsync` in `Worker.cs` to the following

```csharp
protected override async Task ExecuteAsync(CancellationToken stoppingToken)
{
    while (!stoppingToken.IsCancellationRequested)
    {
        _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
        _logger.LogInformation("The secret is: {Secret}", _config["SecretName"]);
        await Task.Delay(1000, stoppingToken);
    }
}
```

3. Set a user secret value: `dotnet user-secrets set "SecretName" "SecretValue"`
4. Run with `dotnet run`

## Expected Results

The secret value is written in a log message like:

```
info: UserSecretsInWorkerRepro.Worker[0]
      Worker running at: 12/05/2019 11:51:07 -08:00
info: UserSecretsInWorkerRepro.Worker[0]
      The secret is: SecretValue
```

## Actual Results

The secret value is not present

```
info: UserSecretsInWorkerRepro.Worker[0]
      Worker running at: 12/05/2019 11:51:07 -08:00
info: UserSecretsInWorkerRepro.Worker[0]
      The secret is: (null)
```

**Comment by hbermani** [comment]
Hi there, is there a workaround for this bug? Kind of stuck here not able to use userSecret in my worker service project :(.

**Comment by poke** [comment]
The easiest workaround, which doesn’t require you to change any of your code, is to add an explicit package reference to the user secrets package.

So in addition to the default reference `Microsoft.Extensions.Hosting`, also explicitly add `Microsoft.Extensions.Configuration.UserSecrets` in your `.csproj` to trigger the mechanism that makes the default host builder setup find your user secrets:

```
<ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="3.1.8" />
</ItemGroup>
```

**Comment by explorer14** [comment]
Sorry, but this is not really a "fix", having a transitive and a direct dependency on the same package makes it confusing to look at  for developers who might look at the two and go, "_hmm..I guess it was an oversight, I will get rid of the direct ref and remove the 'duplication'_", and that will break everyone's local development/debugging. I am a bit shocked that for around a year, this has been peddled as a "fix"!

In the absence of a real fix, the next best thing would be to either:

- Manually add an `AssemblyInfo.cs` into the executable project and add the `UserSecretsId` attribute (_basically what should happen out of the box_), or,

- Do what @hbermani did, that also works i.e. `config.AddUserSecrets(<UserSecretIdFromTheProject.csproj>)`

**Comment by poke** [comment]
@explorer14 
> Sorry, but this is not really a "fix"

Nobody mentioned anything about a fix. The bug is known and this issue is open to track a proper fix.

Since this issue is where people are being pointed when they encounter the problem, it is a useful thing to document the workarounds for it. Which is what was asked for and what I did.

> If its in code then at least it wouldn't be removed without somebody noticing it

The same could be said about explicitly adding the user secret id to the AssemblyInfo.cs (which is usually redundant because things can be specified through the project file) or to the `AddUserSecrets` call (which is redundant because user secrets are already configured through the default host builder).

**Comment by jcotton42** [comment]
Was this fixed in .NET 5? I don't have UserSecrets referenced directly, but they're loading correctly in the Development environment.

**Comment by oising** [comment]
Should this be still open @anurse ?

**Comment by anurse** [comment]
It's been a while since I've checked it and I haven't been working on .NET for a year or so now so I'm not sure. I don't know if it's been fixed or not, but if not I think it's still an unpleasant user experience.

**Comment by oising** [comment]
I tried it out with .net 5 and it worked fine, and incidentally, it
automatically added the usersecrets assembly explicitly.

**Comment by rleopold** [comment]
I just ran into this in .net 5, it's still an issue. Adding MEH package explicitly "fixes" it.

**Comment by KalleOlaviNiemitalo** [comment]
Maybe this could be fixed by adding `buildTransitive` assets (<https://github.com/NuGet/Home/issues/6091>) to the UserSecrets package.

**Comment by baltie** [comment]
Still an issue in .NET 6 RC2 with worker services. Adding a reference to M.E.Configuration.UserSecrets still works as a workaround.

**Comment by eerhardt** [comment]
This issue was also opened in dotnet/runtime (where the UserSecrets package now lives). https://github.com/dotnet/runtime/issues/63246

I plan on fixing this issue using the approach @KalleOlaviNiemitalo outlines above (renaming the `build` folder to `buildTransitive`). I also plan on backporting the fix to `6.0`.

I'm going to close this issue as duplicate of https://github.com/dotnet/runtime/issues/63246, since that is where the fix will be made.
