### ISSUE TITLE
`slnx` support in the `dotnet` CLI

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk#40913]
The `dotnet` CLI should support the new `slnx` format for building and in the existing solution management commands. It should also help interested users migrate to the new format.

### The new format

`slnx` is an XML-based format that simplifies the current `sln` file format. When released, it will have an open-source parser, so tools like MSBuild and the `dotnet` CLI can consistently operate on the format.  The new format is intended to reduce common customer pains like merge conflicts and readability, but not to drastically change the experience of working with solutions.

### `dotnet` experiences using solutions

There are three primary ways that the `dotnet` CLI interacts with solution files today

* building solutions
  * `dotnet build myapp.sln`
* adding or removing projects and other files from solutions
  * `dotnet sln myapp.sln add src/migrations`
* creating new solutions
  * `dotnet new solution -n lodestone`

Each of these should be made to work with the new format to some degree.  In addition, a fourth new capability should be added:

* migrating from `sln` to `slnx`
  * `dotnet sln <sln file> migrate`

#### Building solutions

**Status**: Done, will be shipping in .NET 9.0.200. Available in VS 17.13 preview 2/.NET SDK 9.0.200-preview

This should be mostly transparent to the `dotnet` CLI. Much like solutions today, building a solution involves passing the path to the solution file to the MSBuild engine, which has the sole responsibility of converting the build configurations into a 'metaproject' - a kind of MSBuild representation that MSBuild can actually execute - and then building the requested targets on that metaproject.

The same process would hold with `slnx` - the CLI would forward along the `slnx` file provided (if any) and MSBuild itself would translate that file into a metaproject and execute that metaproject. Very few changes should be required in the CLI codebase to support this. MSBuild's tracking issue for this is https://github.com/dotnet/msbuild/issues/10266.

#### Manipulating solution content

**Status**: In progress - see the linked PRs below.

The CLI has [several commands](https://github.com/dotnet/sdk/blob/1a64a74dc1e630fcd723d40f1472ad4d78feee90/src/Cli/dotnet/commands/dotnet-sln) that allow for adding and removing projects in a solution, as well as listing the existing projects. All of these commands should work with `slnx` as well. This is the area that will require the most investment. The CLI will need to 

* learn that `slnx` files are valid inputs to these commands
* provide some kind of alternative implementation for these commands that works on `slnx` files
* pivot the implementation used based on the file type provided

These commands allow for selection of the solution file. If invoked in a location where multiple potential solution files are present, the command should error and prompt the user to choose one of the possible solutions.

We'll also need to invest in test coverage to make sure we have parity between our `sln` support and `slnx` support.

#### Creating new solutions

**Status**: Done, will be shipping in .NET 9.0.200. Available in VS 17.13 preview 2/.NET SDK 9.0.200-preview

The CLI currently ships a [`solution` template](https://github.com/dotnet/sdk/blob/e2792201ca57a41bd3e1ecd3ae8da0f5743eca43/template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Solution) that create a new, barebones solution file. 

We should provide a template that can create an empty `slnx` file for users to begin with. The new slnx template should use UTF-8 _without a BOM_. One major question: should we supplant the existing `solution` template to create an `slnx` file? Should the old solution format be accessible via a template parameter?

#### Migrating existing solutions

**Status**: Done, will be shipping in .NET 9.0.200. Available in VS 17.13 preview 3

An entirely new capability to migrate a `sln` file to a new `slnx` file should be implemented as well to ease onboarding and allow for automation. This command would load the existing `sln` file and analyze it, translating it into an equivalent `slnx` file. Ideally any data that matches the default conventions of the new `slnx` format (for example, default build configurations like `Debug` and `Release`) could be omitted from the generated `slnx` file. The migrated slnx file will be written alongside the existing solution to allow for easy reverting/recovery of the change. The solution file to act upon will follow our existing `SlnArgument` pattern - if an exact path is used, use that sln. If a directory is provided, and there is only one solution file, use that solution file. If a directory is provided and there are multiple solution files, error.

Note that the addition of this slnx file will likely cause 'bare', unspecified MSBuild commands (like `dotnet build` without an explicit solution argument) as well as `dotnet sln` commands with no arguments to fail when used in the working directory - this is acceptable.  Users can test by explicitly building the new slnx, and then delete the previous .sln file when they are satisfied with the behaviors.

#### References
* [Twitter Survey](https://twitter.com/ChetHusk/status/1786454596463841600)
* [Mastodon survey](https://hachyderm.io/deck/@chethusk/112378449237699210)

**Comment by glen-84** [comment]
Regarding the solution template, would it possible to exclude the byte order mark (BOM) now, or are there still known issues with VS or msbuild?

I know that:

1. The [Unicode Standard](https://www.unicode.org/versions/Unicode5.0.0/ch02.pdf) does not recommend its use.
2. Even applications like Notepad now use UTF-8 without BOM by default. ([source](https://www.bleepingcomputer.com/news/microsoft/windows-10-notepad-is-getting-better-utf-8-encoding-support/))

**Comment by baronfel** [comment]
@glen-84 I'm inclined to make that change, but would like to discuss with @rainersigwald and the rest of the MSBuild team about any gaps there.

**Comment by rainersigwald** [comment]
For `.sln` I would leave it as it has been (I believe that's the longstanding Windows 16-bit chars with BOM).

For `.slnx` we should definitely avoid the BOM but would need to check with the VS folks to make sure they agree.

**Comment by baronfel** [comment]
I've reached out to the VS side to check compatibility with no-BOM.

**Comment by baronfel** [comment]
The VS team confirmed that slnx defaults to UTF-8 No-BOM, so we are clear to default the slnx template contents to no-BOM as well. I've updated the description to match this.

**Comment by vaind** [comment]
Is there any concrete plan for this? I'm looking forward to build/test/restore support for slnx (also when referenced from a .slnf) so that we can update Sentry .NET SDK to use the new format.. Adding projects to the old format is so cumbersome when you need to keep a PR reviewable.

**Comment by baronfel** [comment]
We are still waiting for an official parser library for the new format to be made available by our partner teams. We're unable to make any progress without that library (and the stabilized format spec implied by that)

**Comment by baronfel** [comment]
Not at this time, no.

**Comment by ssg** [comment]
`dotnet test` also parses `sln` files to find test projects and fails to work with `slnx`, fyi.

**Comment by aradalvand** [comment]
Still waiting for this.
Stuff like this makes it feel like Microsoft still sees non-Visual-Studio users of .NET as second-class citizens; which is disappointing after all these years.

**Comment by ite-klass** [comment]
> Still waiting for this. Stuff like this makes it feel like Microsoft still sees non-Visual-Studio users of .NET as second-class citizens; which is disappointing after all these years.

It's not like slnx works very well in VS. It's an experimental preview feature. And even with VS, CI requires dotnet CLI.

**Comment by chucker** [comment]
> Stuff like this makes it feel like Microsoft still sees non-Visual-Studio users of .NET as second-class citizens

It's not a non-preview feature yet in VS (I believe the release notes still don't mention it at all), and the API isn't considered stable.

**Comment by baronfel** [comment]
A status update for those following this issue:

* The new parser is now open-source, and the repository can be found at https://github.com/microsoft/vs-solutionpersistence
* MSBuild has a PR that enables support for building slnx files at https://github.com/dotnet/msbuild/pull/10794
* We will have to wait for the slnx parser to be onboarded to [source-build-externals](https://github.com/dotnet/source-build-externals) before we can merge the MSBuild PR.

Our current plan is to try to merge this change and get support for building slnx files from the .NET SDK in a preview release of the 9.0.200 SDK, but that is subject to some timelines that we are still navigating.

**Comment by baronfel** [comment]
@kasperk81 From the issue description:

>  One major question: should we supplant the existing solution template to create an slnx file? Should the old solution format be accessible via a template parameter?

Switching the defaults for .NET 10 is a fine plan, and is what we had been internally considering anyway.

**Comment by JohnGalt1717** [comment]
you can't build a solution from the cli with slnx files right now with 9.0 RC2... when is this fixed? Is there a work around? It makes the slnx standard useless in all but the hello world case.

**Comment by philipp-naused** [comment]
> you can't build a solution from the cli with slnx files right now with 9.0 RC2... when is this fixed? Is there a work around? It makes the slnx standard useless in all but the hello world case.

The feature is scheduled for `9.0.2xx`. `9.0 RC2` is actually `9.0.100-rc.2`.

**Comment by richshadman** [comment]
Understanding the support policy for .NET favors the even releases, once this is out in the wild with the the .NET 9 release, will the slnx support be brought back into .NET 8, or will we have to wait for 10 for LTS support with slnx in the sdk? 

The slnx format being so much simpler could be very useful for me with complex CICD scenarios - thinking of dynamic slnx files on the fly to target unit tests projects based on code changes, things of that nature. As we are currently bound to the LTS release for maintainability reasons, use of this feature for our team would possibly depend on it being brought into .NET 8 (or wait until 10) as we try to target the same sdk as our target framework (especially for containerized builds and tests where we start with the sdk base image).

**Comment by chucker** [comment]
>The slnx format being so much simpler could be very useful for me with complex CICD scenarios - thinking of dynamic slnx files on the fly to target unit tests projects based on code changes, things of that nature.

Semi-OT, but it sounds like https://github.com/microsoft/slngen might help you.

**Comment by chucker** [comment]
@kasperk81 I know. But the CI/CD, unit test, etc. use case sounded a bit like what slngen is trying to solve.

**Comment by richshadman** [comment]
I'm actually solving it currently with `dotnet new sln` and `dotnet sln add` - works well enough for now. however generating the solution file without being dependent on dotnet cli would give us more flexibility, and slnx is a much simpler format towards that end. Also easier to parse for a human.

**Comment by rainersigwald** [comment]
@richshadman have you considered using MSBuild projects that point to the projects you care about (maybe using [Microsoft.Build.Traversal](https://github.com/microsoft/MSBuildSdks/tree/main/src/Traversal), instead of synthesizing solutions? Then you could have MSBuild conditions, and it'd probably be generally easier to debug.

**Comment by rainersigwald** [comment]
@alrz IMO `.sln`/`.slnx` are _only_ for Visual Studio/C# Dev Kit support.

**Comment by richshadman** [comment]
> [@richshadman](https://github.com/richshadman) have you considered using MSBuild projects that point to the projects you care about (maybe using [Microsoft.Build.Traversal](https://github.com/microsoft/MSBuildSdks/tree/main/src/Traversal), instead of synthesizing solutions? Then you could have MSBuild conditions, and it'd probably be generally easier to debug.

No I have not - I will look into that.

VS 17.12 was released today. Any update on .NET 8 support for slnx by chance?

**Comment by JohnGalt1717** [comment]
I can tell you that in 17.12 and 17.13 P1 don't even support SLNX for jumplists properly, and the upgrade tool also doesn't work.

It's a half-baked mess.

**Comment by bamancio-futura** [comment]
how is this still "untriaged"  ?

**Comment by julealgon** [comment]
> `sln-add` is now available in the daily (net10) build, and I’ve got some strong opinions about the mandatory random GUID it’s adding to each `<Project` node: [#44570 (comment)](https://github.com/dotnet/sdk/pull/44570#issuecomment-2524042134). What do you all think?

Oh boy please don't add guids back in this, that substantially defeats the purpose of the new format.

**Comment by edvilme** [comment]
> `sln-add` is now available in the daily (net10) build, and I’ve got some strong opinions about the mandatory random GUID it’s adding to each `<Project` node: [#44570 (comment)](https://github.com/dotnet/sdk/pull/44570#issuecomment-2524042134). What do you all think?
> 
> The whole point of `.slnx` was to avoid GUIDs wherever possible. Without the `Id={guid}` part in `<Project Path="{path}" Id="{guid}" />`, Visual Studio opens the solution just fine, and MSBuild has no issues building it. So, why is the SDK randomly generating project GUIDs for `.slnx`?
> 
> Currently, if a project file has a `<ProjectGuid>` (legacy) property, it uses that value, which is fine. The problem is when `<ProjectGuid>` isn’t present (which is a common occurrence in modern projects) it randomly generates a GUID, and that’s not the desired behavior.

THanks for pointing this out! You are absolutely right, this is addressed in https://github.com/dotnet/sdk/pull/45366

**Comment by philipp-naused** [comment]
It looks like .NET SDK `9.0.200-preview.0.24575.35` is now included in Visual Studio 2022 `17.13.0-pre.2.0`.
Both the dotnet.exe and MSBuild.exe included in this preview support the new format.

**Comment by edvilme** [comment]
Update: `dotnet sln migrate`, `dotnet sln list`, `dotnet sln add`, `dotnet sln remove` already merged to 9.0.2xx :)

**Comment by philipp-naused** [comment]
Is there an overview of which commands are still missing?
e.g: `dotnet format` https://github.com/dotnet/sdk/blob/bee76bdbc2becae706389ef70ae51171ba199e7a/src/BuiltInTools/dotnet-format/Workspaces/MSBuildWorkspaceFinder.cs#L79C9-L80C110

**Comment by edvilme** [comment]
> Is there an overview of which commands are still missing? e.g: `dotnet format` https://github.com/dotnet/sdk/blob/bee76bdbc2becae706389ef70ae51171ba199e7a/src/BuiltInTools/dotnet-format/Workspaces/MSBuildWorkspaceFinder.cs#L79C9-L80C110 and `dotnet workload restore` https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/commands/dotnet-workload/restore/WorkloadRestoreCommand.cs

Yes, the plan is to currently remove all instances of the previous parser and replace with vs-solutionpersistence, as well as adding discovery for .slnx files in other areas that forward to MSBuild https://github.com/dotnet/sdk/pull/45442

**Comment by julealgon** [comment]
@edvilme when do you expect we will see official `slnx` support completed? Will that be announced as part of a specific Visual Studio update?

I just wanted to keep close track of that so we can jump into it as soon as possible on our side.

**Comment by baronfel** [comment]
Hi @julealgon -

VS _today_ supports building with SLNX files, but the rest of the CLI-based ecosystem does not. In next month's 9.0.200 SDK release (which will ship with VS 17.13), the CLI will be able to support SLNX files as well. Other IDEs like VSCode and Rider may not yet support SLNX still - you'll need to reach out to those products to check their expected timelines.

Even with 9.0.200 supporting SLNX formats, though, the VS IDE itself doesn't have the format enabled as a default. If you'd like to migrate you'll need to enable the option for every developer that will work on your solution.

**Comment by philipp-naused** [comment]
Is there any reason it shouldn't be enabled by default in 17.13?
Why hide it in the "Preview Features" tab if it only adds support for a new format?

**Comment by rainersigwald** [comment]
@kasperk81 that's a pretty different thing. _MSBuild_ handles them in 17.13+ without special flags. That's totally independent of what _Visual Studio_ does.

**Comment by rainersigwald** [comment]
That's a correct description for MSBuild's behavior. For the VS schedule: no, we didn't really coordinate with them, beyond letting them know we were going to use their parser in production (and going back and forth making sure it passed the MSBuild-level tests of solution stuff as well as our old private implementation). We're trying to make sure we don't slow adoption of this feature down once VS feels it's ready to go, but that decision is up to the VS core team.

**Comment by theKBro** [comment]
dotnet list package with slnx still throws an error
"error: Parameter \"xml\" cannot be null."

**Comment by philipp-naused** [comment]
@kasperk81, @theKBro There is already an issue for this: #46763

**Comment by edvilme** [comment]
Hello @kasperk81 yes, we are aware of this regression. When attempting to add projects outside the solution file directory, the cli attempts to create solution folder `..`, which is not a valid solution folder name. A fix for this can be found on #46456 and should be released on 9.0.201

**Comment by philipp-naused** [comment]
`dotnet list` and `dotnet format` are working in 9.0.201

**Comment by baronfel** [comment]
@edvilme @kasperk81's the ToolManifestFinder one is something we should fix, but the source build one we should not touch. That'll only be relevant if/when this repo converts to using slnx, and the source-build team can handle it then.

**Comment by philipp-naused** [comment]
@ownerer, @kasperk81 this only happens when you specify the slnx file explicitly.
If you only type `dotnet format` in a directory that has only a slnx file, it works (in 9.0.201).

**Comment by edvilme** [comment]
> [@edvilme](https://github.com/edvilme) [@kasperk81](https://github.com/kasperk81)'s finding of the ToolManifestFinder one is something we should fix, but the source build one we should not touch. That'll only be relevant if/when this repo converts to using slnx, and the source-build team can handle it then.

Here is the PR. Should we target 9.0.2xx or 9.0.3xx? https://github.com/dotnet/sdk/pull/47512

**Comment by baronfel** [comment]
300 will definitely get in, 200 we'd need to show a user that this actually impacted. Since 200 is such a short support lifetime anyway I'd be ok with just 300.
