### ISSUE TITLE
dotnet 9, "dotnet watch" is really bad in Blazor Server

### ISSUE THREAD

**Issue by qucee98** [dotnet/sdk#45810]
#### Environment: 
* **OS**: Linux Ubuntu 24.04.1 LTS
* **IDE**: Vim/Neovim (non vscode and visual studio IDE)
* **SDK**: 9.0.200-preview.0.24575.35
* **LSP**:   Omnisharp
#

**hot reloading just sucks in dotnet 9** when using Blazor Server... 🤷‍♂️

I migrated my project from .net 8 to .net 9 and followed this doc:
* [Static asset delivery optimization](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?view=aspnetcore-9.0#static-asset-delivery-optimization)
* [Improved server-side reconnection experience](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?view=aspnetcore-9.0#improved-server-side-reconnection-experience)

`dotnet watch` command seems to be inconsistent in reloading the page when making changes to my current buffer.
When it starts to NOT work, then it never works after any changes, i have to restart the project manually.

".NET 9.0.200" patched it a bit, but hot reloading is still inconsistent in reloading the changes.
#44912
#45749 
#45097
#45131

 
#

"Hot Reloading"? more like "Hot Mess".

Switching back to .NET 8 until y'all get your stuff together....

**Comment by XorZy** [comment]
It would be nice if Microsoft could acknowledge this problem and provide a clear ETA for the fix.
As it stands hot reload, which I would argue is essential when working with Blazor apps, is completely broken.
I have to restart the application every time I make the slightest of changes.
NET 9 was first released almost two months ago now, and I don't understand why fixing this issue is not a priority.

**Comment by stephajn** [comment]
It's just as awful in Blazor WASM projects too. Without any other code changes besides updating to .NET 9 and targeting .NET 9 in our projects, Hot Reload went from being something we could depend on and be reliable, to a hot garbage mess that barely functions, even in an ASP.NET Core Web API project, but is especially awful in Blazor projects.
Response from Microsoft has been lackluster, and even almost non-existent with some talks about pushing back fixing it to the .NET 10 milestone which is beyond insane to wait a whole year to fix something that they broke horribly.

Sad to say it, but we just might have to give .NET 9 a pass and go back to .NET 8 if this isn't resolved soon.

**Comment by willdean** [comment]
I'm going to add a me-too, because we all know there's nothing motivates MS quite like a thousand-post Github issue...

This is a blocker on 9 as far as we're concerned and I'm really disappointed that yesterday's release (representing ~17% of the whole release cycle) has failed to make a difference.   TBH, looking in from outside via GH, the whole dotnet project looks poorly, but Blazor particularly so.

At least there's a bright side - if we don't move to 9 because of `dotnet watch`, then at least we don't get caught up in all that static-assets insanity...

**Comment by breakingram** [comment]
Same... I've noticed that I've been manually restarting the Blazor Server a lot more frequently in 9.

**Comment by aaronsmithuk** [comment]
Same. Have been test upgrading and downgrading for weeks now. Come on MS - surely you have the budget to fix one of the most core parts of the MS Dev experience- hot reload! 

@danroth27 save us!

**Comment by aaronsmithuk** [comment]
Just for reference this worked perfectly in .NET 8 (Blazor server and client components in a razor page project) - file save pushed hot reload in about 1 second. 
Upgraded to .NET 9 - (v17.12.4 visual studio ent) - when saving it says "file deleted" - then, nothing! Can't upgrade till this is fixed.

"Watch": {
  "commandName": "Executable",
  "executablePath": "C:\\Program Files\\dotnet\\dotnet.exe",
  "commandLineArgs": "watch run -c $(Configuration)",
  "workingDirectory": "$(ProjectDir)",
  "launchUrl": "https://localhost:5001;http://localhost:5000",
  "environmentVariables": {
    "ASPNETCORE_ENVIRONMENT": "Development"
  }
}

**Comment by aaronsmithuk** [comment]
Using Visual Studio IIS hot reload in .NET 9 - click save, count to 200 and you might get an update. What is happening here!!

**Comment by willdean** [comment]
>  Are you still seeing problems with .NET SDK 9.0.102 that released earlier this week? Note that the corresponding 9.0.200 preview update hasn't shipped yet, but should be available later this month.

Yes.  It seems about the same as before.   (Blazor Server, .NET8 project)

**Comment by stephajn** [comment]
@danroth27 I wanted to give you even more feedback at the server layer regarding Hot Reload. This is for an ASP.NET Core Web API project also running on .NET 9. (Perhaps a different team / issue is needed, but I'm not sure)

Added a new server endpoint on an existing Web API Controller while `dotnet watch` was running. When hot reload kicked in, this is what the console outputted. For the same of this sample, I am calling the API project "SomeProjectName.Api" and the controller's .cs file is named "SomeApiController.cs"

dotnet watch ⌚ File added: .\Controllers\SomeApiController.cs~
dotnet watch ⌚ File updated: .\Controllers\SomeApiController.cs
dotnet watch ⌚ File added: .\Controllers\SomeApiController.cs~
dotnet watch ⌚ File updated: .\Controllers\SomeApiController.cs
dotnet watch ⚠ [SomeProjectName.Api (net9.0)] Expected to find a static method 'ClearCache' or 'UpdateApplication' on type 'Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlAttributePropertyHelper, Microsoft.AspNetCore.Mvc.ViewFeatures, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' but neither exists.
dotnet watch 🔥 [SomeProjectName.Api (net9.0)] Hot reload succeeded.

Again, I hope that this is helpful or useful to you.

**Comment by danroth27** [comment]
@willdean @stephajn Thanks for these additional details.

@phil-allen-msft @tmat Do we know what's going on here?

**Comment by tmat** [comment]
Sounds like multiple potential issues. Any repro with the latest 9.0.2xx build?

**Comment by tmat** [comment]
> dotnet watch ⚠ [SomeProjectName.Api (net9.0)] Expected to find a static method 'ClearCache' or 'UpdateApplication' on type 'Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlAttributePropertyHelper, Microsoft.AspNetCore.Mvc.ViewFeatures, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' but neither exists.

This is fixed by https://github.com/dotnet/aspnetcore/pull/58558 in 10.0 preview.

**Comment by stephajn** [comment]
> Sounds like multiple potential issues. Any repro with the latest 9.0.2xx build?

@tmat I don't have a repro available to recreate this issue, sorry. I could see if I can put something together though.

**Comment by Juulsn** [comment]
I'm also adding a me-too. Using it in combination with aspire. I do know this won't be supported until 9.0.2xx but the fact that it worked way better in .NET 8 than in .NET 9 is disappointing. 
Also had multiple problems in non-aspire context.

Aspire support was why I was ok with using the 9.0.2xx daily builds and since about 1 week it's actually usable now.
However I still see problems like non-reloading of some files without any information in the console, it even says it was successful.

Did open a issue on the sdk repo about this. dotnet/sdk#45197

**Comment by MeikelLP** [comment]
I have this issue in .NET 8 + .NET 9

Hot reload worked fine before .NET 6 with Rider, since it's an "official" feature it's not longer working ever. All my colleagues distrust the "Apply Changes" and restart their aspnetcore app every time which makes development very slow. Especially if you just edit a razor (HTML) file.

I tried `dotnet watch` but I get the warning stated here which is probably the root cause. Very sad to see such a require feature be handled so poorly by Microsoft. Especially in the times of tools like Vite.

**Comment by XorZy** [comment]
> [@phil-allen-msft](https://github.com/phil-allen-msft) [@tmat](https://github.com/tmat)
> 
> [@aaronsmithuk](https://github.com/aaronsmithuk) [@qucee98](https://github.com/qucee98) [@breakingram](https://github.com/breakingram) [@willdean](https://github.com/willdean) [@XorZy](https://github.com/XorZy) [@stephajn](https://github.com/stephajn) Are you still seeing problems with .NET SDK 9.0.102 that released earlier this week? Note that the corresponding 9.0.200 preview update hasn't shipped yet, but should be available later this month.

It appears hot reload of scoped CSS works better in 9.0.102 but overall it still is very slow and crashes often with this error message.

```
Unhandled exception. System.ArgumentException: The renderer does not have a component with ID 0.
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetRequiredComponentState(Int32 componentId)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<RenderRootComponentsOnHotReload>b__53_0()
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<InvokeAsync>g__Execute|8_0(ValueTuple`3 state)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentsOnHotReload()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

dotnet watch ❌ [(net9.0)] Change failed to apply (error code: ''). Further changes won't be applied to this process.

dotnet watch ❌ [(net9.0)] Exited with error code 134
```

**Comment by ArgoZhang** [comment]
@XorZy same issue

**Comment by brettzook** [comment]
I've seen regressions in `dotnet watch` as well after updating to Visual Studio 17.12.3. If I understand correctly, this also installed 9.0.101 of the dotnet sdk, which is now being used when I run the `dotnet` CLI command.

Hot Reload sometimes work, maybe 50% of the time for things that are not of the "rude edit" variety.

But I want to highlight something that @stephajn mentioned:

> After a short time, the application finished restarting, and uselessly opened up a new tab in my browser rather than reloading the existing tab I had open like .NET 8 used to do. Every time the application has to restart it opens a new tab. This is also a completely useless behaviour to me because I want to stay in the tab I was using, and I want to stay on the page I was using rather than starting up from the home page of my application.

I see the same behavior, even in the simplest WASM standalone project. This behavior really interrupts the development loop, as it means closing the old browser tab, going to the new one, and re-opening browser DevTools, in addition to being dropped in the home page of the app rather than the one I was working on.

I've created a separate issue for this behavior:  #46175

**Comment by ArgoZhang** [comment]
the good news in dotnet sdk `9.0.200-preview.0.25057.12` work fine. but shown a new warning.

`Expected to find a static method 'ClearCache' or 'UpdateApplication' on type 'Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlAttributePropertyHelper, Microsoft.AspNetCore.Mvc.ViewFeatures, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' but neither exists`

```
info: Longbow.Tasks.TaskServicesFactory[0]
      01/23/2025 10:20:18 +08:00: TaskServicesFactory StartAsync() Started
info: Longbow.Tasks.TaskServicesFactory[0]
      01/23/2025 10:20:18 +08:00: TaskServicesManager DefaultScheduler(Clear Upload Files) Created
info: Longbow.Tasks.TaskServicesFactory[0]
      01/23/2025 10:20:18 +08:00: SchedulerProcess Start(methodCall) success Called Elapsed: 00:00:00.0004551
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5053
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\Argo\src\BootstrapBlazor\src\BootstrapBlazor.Server
dotnet watch ⌚ File updated: .\Components\Components\Header.razor
dotnet watch ⚠ [BootstrapBlazor.Server (net9.0)] Expected to find a static method 'ClearCache' or 'UpdateApplication' on type 'Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlAttributePropertyHelper, Microsoft.AspNetCore.Mvc.ViewFeatures, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' but neither exists.
dotnet watch 🔥 [BootstrapBlazor.Server (net9.0)] Hot reload succeeded.
```

**Comment by danroth27** [comment]
We believe the original issue reported here is fixed in the latest preview release of .NET SDK 9.0.200, which is available with the latest preview of Visual Studio 17.13. A stable release of 9.0.200 should be available in a few weeks.

We expect to address warning about the missing `ClearCache` or `UpdateApplication` methods in the 9.0.201 patch release, which is expected in March.

We'll follow up on the other separate issues reported here in their corresponding GitHub issues.

Thanks for your patience, folks.

**Comment by aaronsmithuk** [comment]
Up till now, no release fixed my hot reload .NET 9 woes. Until today!

Visual Studio 17.13.0 Preview 5.0 - dotnet.exe watch works perfectly in my major project.

Razor pages with Blazor Server components, changes to .razor files are pushed via hot reload immediately, which is basically the biggest issue.

<TargetFramework>net9.0</TargetFramework>

**Comment by danroth27** [comment]
@aaronsmithuk Awesome! That's great to hear! For those waiting on a stable release, VS 17.13 should be available on the stable channel by the middle of next week assuming everything goes smoothly.

**Comment by aaronsmithuk** [comment]
Just updated to 17.13.0.
Applying a change to Blazor component (simple, just a div with some text) - wait about 2 minutes and it applies.
Next two or three small changes work ok, change applied in about 2 seconds. 
After that - all changes never get applied! Have to shut it all down and start again.
So close, but .NET 8 is still winning!

**Comment by tmat** [comment]
@aaronsmithuk Is this from Visual Studio? 

If so, would you mind filing a VS Feedback ticket?

The following steps will help us investigate:
 
1) Run the following commands from Developer Command Prompt for Visual Studio:

```
*********************************************************************
** Visual Studio 2022 Developer Command Prompt
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************

C:\Program Files\Microsoft Visual Studio\2022\Preview> set Microsoft_CodeAnalysis_EditAndContinue_LogDir=%temp%\HotReloadLog

C:\Program Files\Microsoft Visual Studio\2022\Preview> devenv
```

2) Reproduce the issue in Visual Studio
3) Zip the directory `%temp%\HotReloadLog` and upload it to this ticket on VS Feedback.

**Comment by kjeske** [comment]
I think the fix hasn't been released yet. It's in 9.0.3:
https://github.com/dotnet/aspnetcore/pull/59908

**Comment by angularsen** [comment]
Related 
https://github.com/dotnet/sdk/issues/47179
