### ISSUE TITLE
dotnet watch not releasing .pdb file when restart is requested after a hot reload has occurred

### ISSUE THREAD

**Issue by brettzook** [dotnet/sdk#45831]
### Describe the bug

When running a standalone WASM project via `dotnet watch` within Visual Studio (Developer PowerShell console), a request to restart that occurs after a hot reload will fail, due to the project's .pdb file being held.

This behavior was introduced when I updated to VS 17.12.3 from 17.11.

### To Reproduce

1. Open attached solution `WasmStandalone` in VS.
2. Open Developer Powershell prompt.
1. Run the attached project with `dotnet watch run --project .\WasmStandalone.csproj`
2. Browser will launch to Home.razor.
3. Make a change to some text in Home.razor.
4. Observe dotnet watch handle the change and hot reload (5-10 seconds).
5. Type `Ctl-Shift-R` in the Developer PowerShell console to request a restart
6. Observe error saying pdf file can't be opened for writing; "being used by another process"

Observed sequence:
![Image](https://github.com/user-attachments/assets/0f9fcbbf-a5e7-41bc-8218-629f779df870)

Sample project:
[WasmStandalone.zip](https://github.com/user-attachments/files/18363898/WasmStandalone.zip)

### Further technical details
- `dotnet --info output`

```
PS C:\Source\Samples\WasmStandalone> dotnet --info
.NET SDK:
 Version:           9.0.101
 Commit:            eedb237549
 Workload version:  9.0.100-manifests.4a280210
 MSBuild version:   17.12.12+1cce77968

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.101\

.NET workloads installed:
 [aspire]
   Installation Source: VS 17.12.35527.113
   Manifest Version:    8.2.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.2\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools-net7]
   Installation Source: VS 17.12.35527.113
   Manifest Version:    9.0.0/9.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100\microsoft.net.workload.mono.toolchain.net7\9.0.0\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools]
   Installation Source: VS 17.12.35527.113
   Manifest Version:    9.0.0/9.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100\microsoft.net.workload.mono.toolchain.current\9.0.0\WorkloadManifest.json
   Install Type:              Msi

Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.0
  Architecture: x64
  Commit:       9d5a6a9aa4

.NET SDKs installed:
  5.0.407 [C:\Program Files\dotnet\sdk]
  7.0.410 [C:\Program Files\dotnet\sdk]
  9.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
- Using Visual Studio 17.2.3

**Comment by tmat** [comment]
I believe this has been fixed. Does it reproduce in latest 9.0.2xx build?

**Comment by brettzook** [comment]
Nevermind, just found https://github.com/dotnet/sdk/blob/main/documentation/package-table.md which seems to be the answer.

**Comment by Forgind** [comment]
@brettzook, sounds like you found a 9.0.2xx SDK 4 days ago, so it's fixed now? If I misunderstood, let me know, and we can reopen this 🙂

**Comment by brettzook** [comment]
@Forgind, I hadn't been able to try out the daily build until now, sorry for the delay.

I downloaded and installed `9.0.200-preview.0.25063.22`.

Now when I run `dotnet --version` I see that same value.

I tried the same steps and I still see the error, specifically after a hot reload has occurred. Restarting prior to the hot reload works fine.

![Image](https://github.com/user-attachments/assets/b9553bf3-22f2-476a-aaaf-7b74821e6eb6)

**Comment by Forgind** [comment]
Sounds good. Reopened this issue. @tmat, do you know what the issue is?

**Comment by pimbrouwers** [comment]
I'm experiencing this right now within a vanilla MVC project.

**Comment by brettzook** [comment]
FYI, no change in behavior after updating the SDK to 9.0.200 (stable release).

![Image](https://github.com/user-attachments/assets/5e74b0f8-5122-4c31-8267-ab625d489606)
