### ISSUE TITLE
Targeting net10.0-windows10.0.26100.1 triggers incorrect CsWinRT 3.x warning

### ISSUE THREAD

**Issue by riverar** [dotnet/sdk#51867]
### Describe the bug
Creating a new C# project and targeting Windows 10.0.26100.1 results in strange warnings for frameworks not in use and unreleased.

> C:\Program Files\dotnet\sdk\10.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Windows.targets(199,5): warning NETSDK1229: Targeting a Windows SDK version with '1' as the revision number will reference CsWinRT 3.0, which is currently in preview. The current project is targeting the Windows SDK version ''. If this is not intended, change the revision number to '0' to use CsWinRT 2.x instead.

<img width="572" height="198" alt="Image" src="https://github.com/user-attachments/assets/b5c7a7be-fa36-4d8b-9054-ccdb6b54002d" />

### To Reproduce
1. Create a new C# Console app
2. Target Windows / 10.0.26100.1
3. Build and observe warning

Project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.1</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```

### Further technical details
<details><summary>details of dotnet --info</summary>
<p>
PS C:\Users\Rafael> dotnet --info
.NET SDK:
 Version:           10.0.100
 Commit:            b0f34d51fc
 Workload version:  10.0.100-manifests.5fb86115
 MSBuild version:   18.0.2+b0f34d51f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.26220
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\10.0.100\

.NET workloads installed:
 [maccatalyst]
   Installation Source: VS 18.3.11218.70
   Manifest Version:    26.1.10494/10.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\10.0.100\microsoft.net.sdk.maccatalyst\26.1.10494\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: VS 18.3.11218.70
   Manifest Version:    10.0.0/10.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\10.0.100\microsoft.net.sdk.maui\10.0.0\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 18.3.11218.70
   Manifest Version:    26.1.10494/10.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\10.0.100\microsoft.net.sdk.ios\26.1.10494\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 18.3.11218.70
   Manifest Version:    36.1.2/10.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\10.0.100\microsoft.net.sdk.android\36.1.2\WorkloadManifest.json
   Install Type:              Msi

Configured to use workload sets when installing new manifests.
No workload sets are installed. Run "dotnet workload restore" to install a workload set.

Host:
  Version:      10.0.0
  Architecture: x64
  Commit:       b0f34d51fc

.NET SDKs installed:
  8.0.416 [C:\Program Files\dotnet\sdk]
  10.0.100-rc.1.25451.107 [C:\Program Files\dotnet\sdk]
  10.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 10.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 10.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 10.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</p>
</details>

Visual Studio 2016 Insiders 11218.70

**Comment by marcpopMSFT** [comment]
CC @Sergio0694

**Comment by Sergio0694** [comment]
This is basically the same as that internal ticket from last week. My understanding is that:
- The `.1` TFMs showing up in the "target OS" dropdown are by design, and they're just temporarily not functional until we push a public preview for CsWinRT 3.0.
- The TFMs showing up under "minimum supported OS" are a bug and we should update VS to hide them there.

**Comment by catmanjan** [comment]
I tried this today, and I also got a compiler error: 

`The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.`

Referring to this line `      <_WinRTRuntimeDllDirectory>$([System.IO.Path]::GetDirectoryName('%(_WinRTRuntimeDllReferencePath.FullPath)'))</_WinRTRuntimeDllDirectory>
`

In the file `"C:\Program Files\dotnet\sdk\10.0.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Windows.targets"`

**Comment by Sergio0694** [comment]
Mmh not sure about this error. @catmanjan can you share a binlog? Also cc. @manodasanW.

> "The TFMs showing up under "minimum supported OS" are a bug and we should update VS to hide them there."

Re: this, I'll try to figure out what change we need in VS and drive that.

**Comment by Sergio0694** [comment]
I've made a PR into the .NET project system to filter out the `.1` TFMs from the "Supported OS version" dropdown, it should be available in Visual Studio and Visual Studio Code soon. The `.1` TFMs in the "Target OS version" dropdown are by design, so I don't see anything else left here to address. @marcpopMSFT I don't have permissions in this repo, but we should resolve this 🙂

**Comment by marcpopMSFT** [comment]
@Sergio0694 sounds good. Can you link to the project system PR here so we have that connection?

**Comment by Sergio0694** [comment]
@marcpopMSFT the PR is into the internal repo, not on GitHub (I've been told the one on GitHub is an old mirror) 😅

**Comment by riverar** [comment]
> [...] TFMs in the "Target OS version" dropdown are by design [...]

So are you saying the originally reported error is not fixed and we're just giving up on that?

**Comment by Sergio0694** [comment]
There's nothing to fix, that's by design. It's just temporarily inconvenient because CsWinRT 3.0 isn't released yet. But we can't really update everything exactly at the same time, there's half a dozen of components involved, each with its own release schedule 🥲

**Comment by marcpopMSFT** [comment]
Thanks. Agreed that we typically don't link to internal repos from here. Make sure there is a link to this issue from the internal repo though.

As for what's design or not, I believe you're saying that from the SDK perspective, it's expected that the .1 versions are available but temporarily, you're going to hide them from the dropdown until cswinrt3 is ready for broader consumption. So we are going to take action on this report, just not fixing the .1 versions to work just yet.

**Comment by riverar** [comment]
I don't think he said the Target OS dropdown will see any changes, nor that the warning disappear.

**Comment by Sergio0694** [comment]
> "temporarily, you're going to hide them from the dropdown until cswinrt3 is ready for broader consumption"

No, let me clarify:
- The new TFMs are showing up in the "Target OS version" dropdown. This is completely expected, and by design, because those new TFMs are indeed available from the .NET SDK, and they're usable. Right now they require to also manually set the preview Windows SDK version and to manually reference the CsWinRT preview package, which is also why the .NET SDK is warning. Once we release CsWinRT 3.0 to stable, we'll update the .NET SDK to remove that warning entirely. But these TFMs will always be valid to be listed in this dropdown, no action here.
- The new TFMs are showing up in the "Supported OS version" dropdown. This was not intentional, and they should not be showing up there. My PR into the .NET project system fixed this, so those should go away from there.

Hope this helps 🙂

**Comment by riverar** [comment]
I think the confusion here is a result of Sergio referring to a drop-down that is not part of the bug report. Here's a new screenshot including the drop-down he's referring to:

<img width="585" height="228" alt="Image" src="https://github.com/user-attachments/assets/648470d6-f38d-4ec1-a5c6-d884b9814ad3" />

**Comment by riverar** [comment]
Just need to get something off my chest. I know this isn't on either of you personally.

But this issue is a great example of what's quietly destroying the Windows development experience.

A developer starts a brand-new project, targets a fully GA Windows SDK version with the correct syntax, and is immediately greeted with a warning that (a) doesn't apply to them, (b) references a preview dependency they never opted into, and (c) can't even render the affected framework name correctly, substituting an empty string instead. First impressions matter. This is someone's first impression of using .NET and Windows and it's already broken.

Another passionate developer identifies the UX gap, files an issue, and gets told it's _by design_. Case closed. This is how villains are created.

Meanwhile, the pitch to Windows developers keeps getting louder: use WinUI, use WinRT, package your apps, target the latest SDK, build native Windows apps. But the moment you actually try, the tools punish you for doing exactly what you were told.

**Comment by Sergio0694** [comment]
I understand the frustration Raf, I agree it's not ideal. Thankfully this is just temporary though.

To clarify:

> "a fully GA Windows SDK version with the correct syntax"

This isn't true though. The fully GA Windows SDK version with the correct syntax would be `10.0.26100.0`.

> "doesn't apply to them"

It does apply to them, because they picked a CsWinRT 3.0 TFM.

> "references a preview dependency they never opted into"

They _did_ opt-in though. Selecting a `.1` TFM _is_ how you opt-in. You should just use the normal `.0` for the standard stuff.

> "files an issue, and gets told it's by design. Case closed."

That's not exactly what happened though. We acknowledged that this is not ideal, and shared info that this is only temporary and not what we plan on having in the long term. And we did make a PR to at least improve the experience a bit (in the other dropdown).

I'm not saying everything is perfect, but I would also disagree that things are so broken all around or that we don't care. We do 🙂

**Comment by riverar** [comment]
Thanks all, look forward to the next releases of CsWinRT 2.x and 3.x.
